using System;

namespace Fibonacci
{
    class Fibonacci1
    {
        static void Main(string[] args)
        {
            /* 

            Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

            1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

            By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

            Answer:
            4613732

            */

            int fib = 1, fibprev = 1, sumresult = 0;

            while (fib <= 4000000)
            {
                fib = fib + fibprev;
                fibprev = fib - fibprev;

                if (fib % 2 == 0)
                {
                    sumresult = sumresult + fib;
                }

            }
            Console.WriteLine(sumresult);
        }
    }
}
